baseURL = "/"
languageCode = "fi-FI"
title = "Turvablogi"
defaultContentLanguage = "fi"
enableRobotsTXT = true

[params]
  description = "Turvallisuus edell√§ rakennettu staattinen blogi"
  author = "Atlan"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
